{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bb34345b",
   "metadata": {},
   "outputs": [],
   "source": [
    "// scrape_umd_cs_requirements.js\n",
    "// Usage:\n",
    "// node catalog-scraper/scrape_umd_cs_requirements.js \"https://academiccatalog.umd.edu/undergraduate/colleges-schools/computer-mathematical-natural-sciences/computer-science/computer-science-major/#requirementstext\"\n",
    "\n",
    "import * as cheerio from \"cheerio\";\n",
    "\n",
    "const NUMBER_WORDS = {\n",
    "  one: 1,\n",
    "  two: 2,\n",
    "  three: 3,\n",
    "  four: 4,\n",
    "  five: 5,\n",
    "  six: 6,\n",
    "  seven: 7,\n",
    "  eight: 8,\n",
    "  nine: 9,\n",
    "  ten: 10\n",
    "};\n",
    "\n",
    "function normalizeText(text) {\n",
    "  return (text || \"\")\n",
    "    .replace(/\\u00a0/g, \" \")\n",
    "    .replace(/\\s+/g, \" \")\n",
    "    .trim();\n",
    "}\n",
    "\n",
    "function slugify(text) {\n",
    "  return normalizeText(text)\n",
    "    .toLowerCase()\n",
    "    .replace(/[^a-z0-9]+/g, \"-\")\n",
    "    .replace(/^-+|-+$/g, \"\");\n",
    "}\n",
    "\n",
    "function absoluteUrl(base, relative) {\n",
    "  if (!relative) return null;\n",
    "  try {\n",
    "    return new URL(relative, base).toString();\n",
    "  } catch {\n",
    "    return null;\n",
    "  }\n",
    "}\n",
    "\n",
    "function parseNFromText(text) {\n",
    "  const normalized = normalizeText(text).toLowerCase();\n",
    "\n",
    "  const digitMatch = normalized.match(/\\b(select|choose|take)\\s+(?:at least\\s+)?(\\d+)\\b/i);\n",
    "  if (digitMatch) {\n",
    "    return Number.parseInt(digitMatch[2], 10);\n",
    "  }\n",
    "\n",
    "  const wordMatch = normalized.match(\n",
    "    /\\b(select|choose|take)\\s+(?:at least\\s+)?(one|two|three|four|five|six|seven|eight|nine|ten)\\b/i\n",
    "  );\n",
    "  if (!wordMatch) {\n",
    "    return null;\n",
    "  }\n",
    "\n",
    "  return NUMBER_WORDS[wordMatch[2]] || null;\n",
    "}\n",
    "\n",
    "function extractCourseTokens(text) {\n",
    "  const normalized = normalizeText(text).toUpperCase();\n",
    "  const matches =\n",
    "    normalized.match(/\\b[A-Z]{3,5}(?:\\/[A-Z]{3,5})*\\s*(?:\\d{3}[A-Z]?|[1-4]XX|XXX)\\b/g) || [];\n",
    "\n",
    "  return [...new Set(matches.map(match => normalizeText(match)))];\n",
    "}\n",
    "\n",
    "function extractLinks($, $el, baseUrl) {\n",
    "  const seen = new Set();\n",
    "  const links = [];\n",
    "\n",
    "  $el.find(\"a\").each((_, node) => {\n",
    "    const $a = $(node);\n",
    "    const label = normalizeText($a.text()) || null;\n",
    "    const href = absoluteUrl(baseUrl, $a.attr(\"href\"));\n",
    "    const key = `${label || \"\"}|${href || \"\"}`;\n",
    "\n",
    "    if (seen.has(key)) {\n",
    "      return;\n",
    "    }\n",
    "\n",
    "    seen.add(key);\n",
    "    links.push({ label, href });\n",
    "  });\n",
    "\n",
    "  return links;\n",
    "}\n",
    "\n",
    "function createGroup(kind, description, extras = {}) {\n",
    "  return {\n",
    "    kind,\n",
    "    description: description || null,\n",
    "    rows: [],\n",
    "    subgroups: [],\n",
    "    ...extras\n",
    "  };\n",
    "}\n",
    "\n",
    "function parseCourseRow($, $row, cells, baseUrl) {\n",
    "  const [codeCell, titleCell, creditsCell] = cells;\n",
    "\n",
    "  const rawLabel = normalizeText(codeCell ? codeCell.text() : \"\").replace(/^or\\s+/i, \"\");\n",
    "  const title = normalizeText(titleCell ? titleCell.text() : \"\") || null;\n",
    "  const credits = normalizeText(creditsCell ? creditsCell.text() : \"\") || null;\n",
    "  const links = extractLinks($, $row, baseUrl);\n",
    "  const courseCode = extractCourseTokens(rawLabel || title)[0] || null;\n",
    "\n",
    "  return {\n",
    "    rawLabel: rawLabel || normalizeText($row.text()),\n",
    "    courseCode,\n",
    "    title,\n",
    "    credits,\n",
    "    href: links.length ? links[0].href : null,\n",
    "    links,\n",
    "    alternatives: []\n",
    "  };\n",
    "}\n",
    "\n",
    "function parseParagraphGroup($, $p, baseUrl) {\n",
    "  const text = normalizeText($p.text());\n",
    "  if (!text) {\n",
    "    return null;\n",
    "  }\n",
    "\n",
    "  const links = extractLinks($, $p, baseUrl);\n",
    "  const tokenSet = new Set(extractCourseTokens(text));\n",
    "\n",
    "  for (const link of links) {\n",
    "    if (!link.label) {\n",
    "      continue;\n",
    "    }\n",
    "\n",
    "    for (const token of extractCourseTokens(link.label)) {\n",
    "      tokenSet.add(token);\n",
    "    }\n",
    "  }\n",
    "\n",
    "  if (!tokenSet.size) {\n",
    "    return null;\n",
    "  }\n",
    "\n",
    "  const rows = [...tokenSet].map(token => {\n",
    "    const tokenLink = links.find(link => normalizeText(link.label || \"\").toUpperCase() === token) || null;\n",
    "    return {\n",
    "      rawLabel: token,\n",
    "      courseCode: token,\n",
    "      title: null,\n",
    "      credits: null,\n",
    "      href: tokenLink ? tokenLink.href : null,\n",
    "      links: tokenLink ? [tokenLink] : [],\n",
    "      alternatives: []\n",
    "    };\n",
    "  });\n",
    "\n",
    "  const n = parseNFromText(text);\n",
    "  return {\n",
    "    kind: n ? \"n-of\" : \"all\",\n",
    "    n: n || undefined,\n",
    "    description: text,\n",
    "    rows,\n",
    "    subgroups: [],\n",
    "    source: \"paragraph\"\n",
    "  };\n",
    "}\n",
    "\n",
    "function isSelectionInstruction(text) {\n",
    "  const normalized = normalizeText(text);\n",
    "  return /\\b(select|choose|take)\\b/i.test(normalized) && /\\b(course|credits?|following)\\b/i.test(normalized);\n",
    "}\n",
    "\n",
    "function isAreaLabel(text) {\n",
    "  return /^Area\\s+\\d+:/i.test(normalizeText(text));\n",
    "}\n",
    "\n",
    "function parseTableIntoGroups($, $table, baseUrl) {\n",
    "  const topLevelGroups = [];\n",
    "\n",
    "  let activeTopGroup = null;\n",
    "  let activeSelectGroup = null;\n",
    "  let activeAreaGroup = null;\n",
    "  let lastCourseRow = null;\n",
    "\n",
    "  function getTargetGroup() {\n",
    "    if (activeAreaGroup) return activeAreaGroup;\n",
    "    if (activeSelectGroup) return activeSelectGroup;\n",
    "    if (activeTopGroup) return activeTopGroup;\n",
    "\n",
    "    const fallback = createGroup(\"all\", \"Uncategorized Requirements\");\n",
    "    topLevelGroups.push(fallback);\n",
    "    activeTopGroup = fallback;\n",
    "    return fallback;\n",
    "  }\n",
    "\n",
    "  function startTopLevelGroup(description, credits, links) {\n",
    "    const group = createGroup(\"all\", description, {\n",
    "      creditsRequirement: credits || null,\n",
    "      links: links || []\n",
    "    });\n",
    "    topLevelGroups.push(group);\n",
    "    activeTopGroup = group;\n",
    "    activeSelectGroup = null;\n",
    "    activeAreaGroup = null;\n",
    "    lastCourseRow = null;\n",
    "  }\n",
    "\n",
    "  function startSelectGroup(description, credits, links) {\n",
    "    const n = parseNFromText(description);\n",
    "    const group = createGroup(n ? \"n-of\" : \"all\", description, {\n",
    "      n: n || undefined,\n",
    "      creditsRequirement: credits || null,\n",
    "      links: links || []\n",
    "    });\n",
    "\n",
    "    const parent = activeAreaGroup || activeTopGroup;\n",
    "    if (parent) {\n",
    "      parent.subgroups.push(group);\n",
    "    } else {\n",
    "      topLevelGroups.push(group);\n",
    "    }\n",
    "\n",
    "    activeSelectGroup = group;\n",
    "    activeAreaGroup = null;\n",
    "    lastCourseRow = null;\n",
    "  }\n",
    "\n",
    "  function startAreaGroup(description, credits, links) {\n",
    "    const group = createGroup(\"all\", description, {\n",
    "      creditsRequirement: credits || null,\n",
    "      links: links || []\n",
    "    });\n",
    "\n",
    "    if (activeSelectGroup) {\n",
    "      activeSelectGroup.subgroups.push(group);\n",
    "    } else if (activeTopGroup) {\n",
    "      activeTopGroup.subgroups.push(group);\n",
    "    } else {\n",
    "      topLevelGroups.push(group);\n",
    "    }\n",
    "\n",
    "    activeAreaGroup = group;\n",
    "    lastCourseRow = null;\n",
    "  }\n",
    "\n",
    "  $table.find(\"tr\").each((_, tr) => {\n",
    "    const $row = $(tr);\n",
    "    const cells = $row.find(\"th,td\").toArray().map(cell => $(cell));\n",
    "    if (!cells.length) {\n",
    "      return;\n",
    "    }\n",
    "\n",
    "    const firstTag = (cells[0].prop(\"tagName\") || \"\").toLowerCase();\n",
    "    if (firstTag === \"th\") {\n",
    "      return;\n",
    "    }\n",
    "\n",
    "    const rowClass = ($row.attr(\"class\") || \"\").toLowerCase();\n",
    "    const firstCellText = normalizeText(cells[0].text());\n",
    "    const rowText = normalizeText(cells.map(c => c.text()).join(\" \"));\n",
    "\n",
    "    if (!rowText) {\n",
    "      return;\n",
    "    }\n",
    "\n",
    "    const credits = normalizeText(cells[cells.length - 1].text()) || null;\n",
    "    const links = extractLinks($, $row, baseUrl);\n",
    "\n",
    "    if (/^total credits$/i.test(firstCellText)) {\n",
    "      startTopLevelGroup(\"Total Credits\", credits, links);\n",
    "      return;\n",
    "    }\n",
    "\n",
    "    const isHeader = rowClass.includes(\"areaheader\") || isSelectionInstruction(firstCellText || rowText);\n",
    "    if (isHeader) {\n",
    "      const description = firstCellText || rowText;\n",
    "\n",
    "      if (isAreaLabel(description)) {\n",
    "        startAreaGroup(description, credits, links);\n",
    "        return;\n",
    "      }\n",
    "\n",
    "      if (isSelectionInstruction(description)) {\n",
    "        startSelectGroup(description, credits, links);\n",
    "        return;\n",
    "      }\n",
    "\n",
    "      startTopLevelGroup(description, credits, links);\n",
    "      return;\n",
    "    }\n",
    "\n",
    "    const row = parseCourseRow($, $row, cells, baseUrl);\n",
    "    const isAlternative = rowClass.includes(\"orclass\") || /^or\\s+/i.test(firstCellText);\n",
    "\n",
    "    if (isAlternative && lastCourseRow) {\n",
    "      lastCourseRow.alternatives.push(row);\n",
    "      return;\n",
    "    }\n",
    "\n",
    "    const target = getTargetGroup();\n",
    "    target.rows.push(row);\n",
    "    lastCourseRow = row;\n",
    "  });\n",
    "\n",
    "  return topLevelGroups;\n",
    "}\n",
    "\n",
    "async function scrape(url) {\n",
    "  const response = await fetch(url);\n",
    "  if (!response.ok) {\n",
    "    throw new Error(`Failed to fetch URL: ${response.status} ${response.statusText}`);\n",
    "  }\n",
    "\n",
    "  const html = await response.text();\n",
    "  const $ = cheerio.load(html);\n",
    "  const $container = $(\"#requirementstextcontainer\").first();\n",
    "\n",
    "  if (!$container.length) {\n",
    "    throw new Error(\"Could not find #requirementstextcontainer on page\");\n",
    "  }\n",
    "\n",
    "  const sections = [];\n",
    "  let currentSection = { id: \"general-track\", title: \"General Track\", requirementGroups: [] };\n",
    "  sections.push(currentSection);\n",
    "\n",
    "  $container.children().each((_, node) => {\n",
    "    const $el = $(node);\n",
    "    const tag = ($el.prop(\"tagName\") || \"\").toLowerCase();\n",
    "\n",
    "    if (tag === \"h2\") {\n",
    "      const title = normalizeText($el.text());\n",
    "      if (title) {\n",
    "        currentSection = { id: slugify(title), title, requirementGroups: [] };\n",
    "        sections.push(currentSection);\n",
    "      }\n",
    "      return;\n",
    "    }\n",
    "\n",
    "    if (tag === \"p\") {\n",
    "      const paragraphGroup = parseParagraphGroup($, $el, url);\n",
    "      if (paragraphGroup) {\n",
    "        currentSection.requirementGroups.push(paragraphGroup);\n",
    "      }\n",
    "      return;\n",
    "    }\n",
    "\n",
    "    if (tag === \"table\") {\n",
    "      currentSection.requirementGroups.push(...parseTableIntoGroups($, $el, url));\n",
    "    }\n",
    "  });\n",
    "\n",
    "  return {\n",
    "    url,\n",
    "    scrapedAt: new Date().toISOString(),\n",
    "    sections\n",
    "  };\n",
    "}\n",
    "\n",
    "if (import.meta.url === `file://${process.argv[1]}`) {\n",
    "  const url =\n",
    "    process.argv[2] ||\n",
    "    \"https://academiccatalog.umd.edu/undergraduate/colleges-schools/computer-mathematical-natural-sciences/computer-science/computer-science-major/#requirementstext\";\n",
    "\n",
    "  scrape(url)\n",
    "    .then(result => {\n",
    "      console.log(JSON.stringify(result, null, 2));\n",
    "    })\n",
    "    .catch(error => {\n",
    "      console.error(error);\n",
    "      process.exit(1);\n",
    "    });\n",
    "}\n",
    "\n",
    "export { scrape };\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
